apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: marwanmuhammad/nodejs.org:latest
        ports:
        - containerPort: 3000
